# 베이스 이미지
FROM wordpress:5.8-apache

# RDS 변수 정의
ENV WORDPRESS_DB_HOST=db-hs1.cluster-cdy6a8acgxti.ap-northeast-2.rds.amazonaws.com
ENV WORDPRESS_DB_PASSWORD=Amazon1!
ENV WORDPRESS_DB_USER=admin
ENV WORDPRESS_DB_NAME=dbhouse

# 포트 개방
EXPOSE 80

