apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      # 이미지 ECR의 최신 버전 사용
      - image: 730335456215.dkr.ecr.ap-northeast-2.amazonaws.com/wordpress-ecr:latest
        name: wordpress
        # ENV로 RDS 변수 설정
        env:
        - name: WORDPRESS_DB_HOST
          value: "db-hs1.cluster-cdy6a8acgxti.ap-northeast-2.rds.amazonaws.com"
        - name: WORDPRESS_DB_PASSWORD
          value: "Amazon1!"
        - name: WORDPRESS_DB_USER
          value: "admin"
        - name: WORDPRESS_DB_NAME
          value: "dbhouse2"
        ports:
        - containerPort: 80
          name: wordpress
        # mountPath로 wp-content 정의 테마와 플러그인, 미디어 등 efs에 저장  
        volumeMounts:
        - name: wordpress-content-storage
          mountPath: /var/www/html/wp-content
      volumes:
      - name: wordpress-content-storage
        persistentVolumeClaim:
          claimName: wordpress-efs-pvc
