apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
     containers:
        - image: wordpress:5.8-apache
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: "db-hs1.cluster-cdy6a8acgxti.ap-northeast-2.rds.amazonaws.com"
            - name: WORDPRESS_DB_PASSWORD
              value: "Amazon1!"
            - name: WORDPRESS_DB_USER
              value: "admin"
            - name: WORDPRESS_DB_NAME
              value: "dbhouse"
          ports:
            - containerPort: 80
              name: wordpress


