apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: hs-db.cluster-cdy6a8acgxti.ap-northeast-2.rds.amazonaws.com
        - name: WORDPRESS_DB_USER
          value: postgres
        - name: WORDPRESS_DB_PASSWORD
          value: Amazon1!
        - name: WORDPRESS_DB_NAME
          value: house
        ports:
        - containerPort: 80

